# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: facebook_devise_development
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: ddbkcapnn68bi9
  username: zycwtjqphkqerw
  password: oPZTJgpQHkoQarmC8Fo8mhqwOb
  host: ec2-54-243-48-227.compute-1.amazonaws.com # something like ec2-xxx-xx-xxx-xxxx.compute-1.amazonaws.com
  sslmode: require